// Generated by Apple Swift version 1.2 (swiftlang-602.0.53.1 clang-602.0.53)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
#endif
#if __has_feature(nullability)
#  define SWIFT_NULLABILITY(X) X
#else
# if !defined(__nonnull)
#  define __nonnull
# endif
# if !defined(__nullable)
#  define __nullable
# endif
# if !defined(__null_unspecified)
#  define __null_unspecified
# endif
#  define SWIFT_NULLABILITY(X)
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import CoreGraphics;
@import ObjectiveC;
@import Foundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSURL;
@class UIImage;
@class NSCoder;

SWIFT_CLASS("_TtC11PDSRecorder11AsyncButton")
@interface AsyncButton : UIButton
- (void)setImageURL:(NSURL * __nullable)url placeholderImage:(UIImage * __nullable)placeholder forState:(UIControlState)state;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder14AsyncImageView")
@interface AsyncImageView : UIImageView
@property (nonatomic) UIImage * __nullable placeholderImage;
@property (nonatomic) NSURL * __nullable url;
- (void)setURL:(NSURL * __nullable)url placeholderImage:(UIImage * __nullable)placeholderImage;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSTextContainer;

SWIFT_CLASS("_TtC11PDSRecorder12AutoTextView")
@interface AutoTextView : UITextView
- (CGSize)intrinsicContentSize;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class CALayer;

SWIFT_PROTOCOL("_TtP11PDSRecorder10Springable_")
@protocol Springable
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic, readonly) CALayer * __nonnull layer;
@property (nonatomic) CGAffineTransform transform;
@property (nonatomic) CGFloat alpha;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
@end


SWIFT_CLASS("_TtC11PDSRecorder12SpringButton")
@interface SpringButton : UIButton <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;

SWIFT_CLASS("_TtC11PDSRecorder16DesignableButton")
@interface DesignableButton : SpringButton
@property (nonatomic) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) UIColor * __nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder15SpringImageView")
@interface SpringImageView : UIImageView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder19DesignableImageView")
@interface DesignableImageView : SpringImageView
@property (nonatomic) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithImage:(UIImage * __null_unspecified)image highlightedImage:(UIImage * __nullable)highlightedImage OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder11SpringLabel")
@interface SpringLabel : UILabel <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder15DesignableLabel")
@interface DesignableLabel : SpringLabel
@property (nonatomic) CGFloat lineHeight;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder15SpringTextField")
@interface SpringTextField : UITextField <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder19DesignableTextField")
@interface DesignableTextField : SpringTextField
@property (nonatomic) UIColor * __nonnull placeholderColor;
@property (nonatomic) CGFloat sidePadding;
@property (nonatomic) CGFloat leftPadding;
@property (nonatomic) CGFloat rightPadding;
@property (nonatomic) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder14SpringTextView")
@interface SpringTextView : UITextView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder18DesignableTextView")
@interface DesignableTextView : SpringTextView
@property (nonatomic) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGFloat lineHeight;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * __nullable)textContainer OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder10SpringView")
@interface SpringView : UIView <Springable>
@property (nonatomic) BOOL autostart;
@property (nonatomic) BOOL autohide;
@property (nonatomic, copy) NSString * __nonnull animation;
@property (nonatomic) CGFloat force;
@property (nonatomic) CGFloat delay;
@property (nonatomic) CGFloat duration;
@property (nonatomic) CGFloat damping;
@property (nonatomic) CGFloat velocity;
@property (nonatomic) float repeatCount;
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat scaleX;
@property (nonatomic) CGFloat scaleY;
@property (nonatomic) CGFloat rotate;
@property (nonatomic, copy) NSString * __nonnull curve;
@property (nonatomic) CGFloat opacity;
@property (nonatomic) BOOL animateFrom;
- (void)awakeFromNib;
- (void)layoutSubviews;
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder14DesignableView")
@interface DesignableView : SpringView
@property (nonatomic) UIColor * __nonnull borderColor;
@property (nonatomic) CGFloat borderWidth;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) UIColor * __nonnull shadowColor;
@property (nonatomic) CGFloat shadowRadius;
@property (nonatomic) CGFloat shadowOpacity;
@property (nonatomic) CGFloat shadowOffsetY;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithCoder:(NSCoder * __nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder24KeyboardLayoutConstraint")
@interface KeyboardLayoutConstraint : NSLayoutConstraint
- (void)awakeFromNib;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder18PDSRecorderManager")
@interface PDSRecorderManager : NSObject
- (void)testManage;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder11SoundPlayer")
@interface SoundPlayer : NSObject
- (void)playSound:(NSString * __nonnull)soundFile;
- (IBAction)play:(id __nullable)sender;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder6Spring")
@interface Spring : NSObject
- (void)animate;
- (void)animateNext:(void (^ __nonnull)(void))completion;
- (void)animateTo;
- (void)animateToNext:(void (^ __nonnull)(void))completion;
- (void)customAwakeFromNib;
- (void)customLayoutSubviews;
@end


SWIFT_CLASS("_TtC11PDSRecorder15SpringAnimation")
@interface SpringAnimation
+ (void)spring:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springEaseIn:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springEaseOut:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springEaseInOut:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springLinear:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations;
+ (void)springWithDelay:(NSTimeInterval)duration delay:(NSTimeInterval)delay animations:(void (^ __null_unspecified)(void))animations;
+ (void)springWithCompletion:(NSTimeInterval)duration animations:(void (^ __null_unspecified)(void))animations completion:(void (^ __null_unspecified)(BOOL))completion;
@end








@protocol UIViewControllerContextTransitioning;
@class UIViewController;

SWIFT_CLASS("_TtC11PDSRecorder17TransitionManager")
@interface TransitionManager : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForPresentedController:(UIViewController * __nonnull)presented presentingController:(UIViewController * __nonnull)presenting sourceController:(UIViewController * __nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForDismissedController:(UIViewController * __nonnull)dismissed;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC11PDSRecorder14TransitionZoom")
@interface TransitionZoom : NSObject <UIViewControllerTransitioningDelegate, UIViewControllerAnimatedTransitioning>
- (void)animateTransition:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (NSTimeInterval)transitionDuration:(id <UIViewControllerContextTransitioning> __nonnull)transitionContext;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForPresentedController:(UIViewController * __nonnull)presented presentingController:(UIViewController * __nonnull)presenting sourceController:(UIViewController * __nonnull)source;
- (id <UIViewControllerAnimatedTransitioning> __nullable)animationControllerForDismissedController:(UIViewController * __nonnull)dismissed;
- (SWIFT_NULLABILITY(nonnull) instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIColor (SWIFT_EXTENSION(PDSRecorder))
- (SWIFT_NULLABILITY(nonnull) instancetype)initWithHex:(NSString * __nonnull)hex;
@end


@interface UIImage (SWIFT_EXTENSION(PDSRecorder))
@end


@interface UIView (SWIFT_EXTENSION(PDSRecorder))
- (void)showLoading;
- (void)hideLoading;
@end

@class UIStoryboardSegue;

@interface UIViewController (SWIFT_EXTENSION(PDSRecorder))
- (IBAction)unwindToViewController:(UIStoryboardSegue * __nonnull)sender;
@end

#pragma clang diagnostic pop
